import Link from "next/link";
import { ArrowUpRight, BadgeCheck, KeyRound, RadioTower, ShieldCheck } from "lucide-react";
import type { Locale } from "@/app/lib/paper3/catalog";
import { paper3Href } from "./shared";
import styles from "./ChapterAdvancedOverview.module.css";

const branches = [
  { icon: KeyRound, title: { en: "Protect confidentiality", vi: "Bảo vệ tính bí mật" }, question: { en: "Which key is used, by whom, and for what purpose?", vi: "Ai dùng khóa nào và nhằm mục đích gì?" }, topics: [["confidentiality-and-key-choice", "Choose symmetric or asymmetric keys", "Chọn khóa đối xứng hoặc bất đối xứng"]] },
  { icon: RadioTower, title: { en: "Detect interception", vi: "Phát hiện nghe lén" }, question: { en: "What evidence reveals that a channel has been observed?", vi: "Bằng chứng nào cho thấy kênh truyền đã bị quan sát?" }, topics: [["quantum-cryptography", "Reason about measurement and disturbance", "Lập luận về phép đo và sự xáo trộn"]] },
  { icon: BadgeCheck, title: { en: "Establish trust online", vi: "Thiết lập niềm tin trực tuyến" }, question: { en: "How do handshake, certificate and signature claims differ?", vi: "Handshake, certificate và signature chứng minh những điều khác nhau ra sao?" }, topics: [["ssl-tls-communication", "Trace the TLS exchange", "Theo dõi trao đổi TLS"], ["certificates-and-signatures", "Separate identity, integrity and authenticity", "Phân biệt danh tính, toàn vẹn và xác thực"]] },
] as const;

export function Chapter17Overview({ locale }: { readonly locale: Locale }) { const vi = locale === "vi"; return <section className={styles.overview} aria-labelledby="chapter17-overview-title"><div className={styles.heading}><div><span>{vi ? "LỘ TRÌNH ÔN THI" : "EXAM LEARNING ROUTE"}</span><h2 id="chapter17-overview-title">{vi ? "Dữ liệu được giữ bí mật và người nhận biết mình đang tin ai bằng cách nào?" : "How is data kept confidential, and how does a receiver know whom to trust?"}</h2></div><p>{vi ? "Mỗi cơ chế giải quyết một claim khác nhau. Khi làm bài, gọi đúng claim trước rồi mới chọn key, protocol hoặc certificate evidence phù hợp." : "Each mechanism supports a different claim. In an exam, name the claim first, then select the key, protocol or certificate evidence that supports it."}</p></div><div className={styles.branches} data-count={branches.length}>{branches.map((branch) => <article className={styles.branch} key={branch.title.en}><header><div><branch.icon size={22} aria-hidden="true" /><span>{vi ? "NHÁNH TƯ DUY" : "THINKING BRANCH"}</span></div><h3>{branch.title[locale]}</h3><p>{branch.question[locale]}</p></header><ol className={styles.route}>{branch.topics.map(([slug,en,viTitle], index) => <li key={slug}><Link href={paper3Href(`/paper-3/topics/${slug}`, locale)}><span className={styles.step}>{index + 1}</span><strong>{vi ? viTitle : en}</strong><ArrowUpRight size={16} aria-hidden="true" /></Link></li>)}</ol></article>)}</div><aside className={styles.prerequisite}><ShieldCheck size={22} aria-hidden="true" /><div><strong>{vi ? "Kiến thức cần gọi lại" : "Prerequisite checkpoint"}</strong><p>{vi ? "Phân biệt plaintext, ciphertext, encryption/decryption và ba mục tiêu confidentiality, integrity, authentication. Không dùng các thuật ngữ này thay thế cho nhau." : "Distinguish plaintext, ciphertext, encryption/decryption, and the separate goals of confidentiality, integrity and authentication."}</p></div></aside></section>; }
