import Link from "next/link";
import { ArrowUpRight, BrainCircuit, GitFork, LineChart, Route } from "lucide-react";
import type { Locale } from "@/app/lib/paper3/catalog";
import { paper3Href } from "./shared";
import styles from "./ChapterAdvancedOverview.module.css";

const branches = [
  { icon: Route, title: { en: "Search a state space", vi: "Tìm kiếm trong không gian trạng thái" }, question: { en: "Which candidate should be expanded next, and why?", vi: "Ứng viên nào được mở rộng tiếp theo, và vì sao?" }, topics: [["graphs-and-dijkstra", "Build shortest known distances", "Xây khoảng cách ngắn nhất đã biết"], ["a-star-and-heuristic-search", "Combine path cost and heuristic", "Kết hợp path cost với heuristic"]] },
  { icon: BrainCircuit, title: { en: "Learn a representation", vi: "Học một biểu diễn" }, question: { en: "What signal changes a model's parameters?", vi: "Tín hiệu nào làm thay đổi tham số của mô hình?" }, topics: [["learning-categories", "Identify the feedback available", "Xác định loại phản hồi có sẵn"], ["neural-networks-and-deep-learning", "Trace activations through a network", "Theo dõi activation qua mạng"], ["backpropagation", "Trace error back to the weights", "Theo dõi error quay về các weight"]] },
  { icon: LineChart, title: { en: "Fit and judge a prediction", vi: "Khớp và đánh giá dự đoán" }, question: { en: "How well does the model explain a numerical trend?", vi: "Mô hình giải thích xu hướng số tốt đến đâu?" }, topics: [["regression", "Fit a line and interpret residuals", "Khớp đường và diễn giải residual"]] },
] as const;

export function Chapter18Overview({ locale }: { readonly locale: Locale }) { const vi = locale === "vi"; return <section className={styles.overview} aria-labelledby="chapter18-overview-title"><div className={styles.heading}><div><span>{vi ? "LỘ TRÌNH ÔN THI" : "EXAM LEARNING ROUTE"}</span><h2 id="chapter18-overview-title">{vi ? "Máy chọn đường đi hoặc cải thiện dự đoán từ thông tin sẵn có như thế nào?" : "How does a machine choose a route or improve a prediction from available information?"}</h2></div><p>{vi ? "Tách rõ search state và learning state. Với search, trace frontier và cost. Với learning, xác định data/feedback rồi trace parameter hoặc prediction change." : "Keep search state separate from learning state. For search, trace the frontier and costs. For learning, identify the data and feedback, then trace the parameter or prediction change."}</p></div><div className={styles.branches} data-count={branches.length}>{branches.map((branch) => <article className={styles.branch} key={branch.title.en}><header><div><branch.icon size={22} aria-hidden="true" /><span>{vi ? "NHÁNH TƯ DUY" : "THINKING BRANCH"}</span></div><h3>{branch.title[locale]}</h3><p>{branch.question[locale]}</p></header><ol className={styles.route}>{branch.topics.map(([slug,en,viTitle], index) => <li key={slug}><Link href={paper3Href(`/paper-3/topics/${slug}`, locale)}><span className={styles.step}>{index + 1}</span><strong>{vi ? viTitle : en}</strong><ArrowUpRight size={16} aria-hidden="true" /></Link></li>)}</ol></article>)}</div><aside className={styles.prerequisite}><GitFork size={22} aria-hidden="true" /><div><strong>{vi ? "Kiến thức cần gọi lại" : "Prerequisite checkpoint"}</strong><p>{vi ? "Ôn node, edge, weight, bảng trace, đại số cơ bản và cách đọc biểu đồ. Mỗi kết luận thi phải chỉ ra state hoặc bằng chứng số hỗ trợ." : "Recall nodes, edges, weights, trace tables, basic algebra and chart reading. Support each exam conclusion with a state change or numerical evidence."}</p></div></aside></section>; }
