import Link from "next/link";
import { ArrowUpRight, Boxes, GitCompareArrows, ListTree, Repeat2 } from "lucide-react";
import type { Locale } from "@/app/lib/paper3/catalog";
import { paper3Href } from "./shared";
import styles from "./ChapterAdvancedOverview.module.css";

const branches = [
  { icon: GitCompareArrows, title: { en: "Search, sort and measure", vi: "Tìm, sắp xếp và đo lường" }, question: { en: "Which invariant explains the next comparison or movement?", vi: "Invariant nào giải thích phép so sánh hoặc dịch chuyển tiếp theo?" }, topics: [["linear-search", "Trace a linear search", "Trace linear search"], ["binary-search", "Maintain binary-search bounds", "Duy trì biên của binary search"], ["bubble-sort", "Trace passes and swaps", "Trace pass và swap"], ["insertion-sort", "Insert into the sorted prefix", "Chèn vào prefix đã sắp xếp"], ["time-and-space-complexity", "Compare resource growth", "So sánh mức tăng tài nguyên"]] },
  { icon: Boxes, title: { en: "Choose and operate an ADT", vi: "Chọn và thao tác ADT" }, question: { en: "Which access rule matches the problem's required behaviour?", vi: "Quy tắc truy cập nào phù hợp hành vi bài toán?" }, topics: [["stack", "Use LIFO operations", "Dùng thao tác LIFO"], ["queue", "Use FIFO operations", "Dùng thao tác FIFO"], ["linked-list", "Follow pointers and free nodes", "Theo pointer và node trống"], ["binary-tree", "Navigate ordered branches", "Đi qua các nhánh có thứ tự"], ["dictionary", "Map keys to values", "Ánh xạ key sang value"], ["implementing-one-adt-with-another", "Separate interface from implementation", "Tách interface khỏi implementation"]] },
  { icon: Repeat2, title: { en: "Design a recursive solution", vi: "Thiết kế lời giải đệ quy" }, question: { en: "What gets smaller, and when can the call return?", vi: "Đại lượng nào nhỏ dần, và khi nào lời gọi có thể trả về?" }, topics: [["designing-and-tracing-recursion", "Define base and recursive cases", "Xác định base case và recursive case"], ["call-stacks-and-unwinding", "Trace calls and unwinding", "Trace lời gọi và quá trình trả về"]] },
] as const;

export function Chapter19Overview({ locale }: { readonly locale: Locale }) { const vi = locale === "vi"; return <section className={styles.overview} aria-labelledby="chapter19-overview-title"><div className={styles.heading}><div><span>{vi ? "LỘ TRÌNH ÔN THI" : "EXAM LEARNING ROUTE"}</span><h2 id="chapter19-overview-title">{vi ? "Chọn cấu trúc và thuật toán nào để state tiến gần đáp án một cách đúng đắn?" : "Which structure and algorithm move the state towards a correct answer?"}</h2></div><p>{vi ? "Mọi bài trace đều dựa trên invariant: phần nào đã tìm, đã sắp xếp hoặc phải giữ nguyên. Ghi state sau từng thao tác rồi giải thích bằng quy tắc của thuật toán hoặc ADT." : "Every trace depends on an invariant: what has been searched, sorted or preserved. Record the state after each operation, then justify it using the algorithm or ADT rule."}</p></div><div className={styles.branches} data-count={branches.length}>{branches.map((branch) => <article className={styles.branch} key={branch.title.en}><header><div><branch.icon size={22} aria-hidden="true" /><span>{vi ? "NHÁNH TƯ DUY" : "THINKING BRANCH"}</span></div><h3>{branch.title[locale]}</h3><p>{branch.question[locale]}</p></header><ol className={styles.route}>{branch.topics.map(([slug,en,viTitle], index) => <li key={slug}><Link href={paper3Href(`/paper-3/topics/${slug}`, locale)}><span className={styles.step}>{index + 1}</span><strong>{vi ? viTitle : en}</strong><ArrowUpRight size={16} aria-hidden="true" /></Link></li>)}</ol></article>)}</div><aside className={styles.prerequisite}><ListTree size={22} aria-hidden="true" /><div><strong>{vi ? "Kiến thức cần gọi lại" : "Prerequisite checkpoint"}</strong><p>{vi ? "Ôn array index, record, pointer, procedure/function và trace table. Luôn phân biệt giá trị dữ liệu với địa chỉ/chỉ số lưu nó." : "Recall array indices, records, pointers, procedures/functions and trace tables. Keep a data value distinct from the address or index that stores it."}</p></div></aside></section>; }
