import Link from "next/link";
import { ArrowUpRight, Braces, FileCog, Layers3, Workflow } from "lucide-react";
import type { Locale } from "@/app/lib/paper3/catalog";
import { paper3Href } from "./shared";
import styles from "./ChapterAdvancedOverview.module.css";

const branches = [
  { icon: Workflow, title: { en: "Choose a programming model", vi: "Chọn mô hình lập trình" }, question: { en: "Which model best expresses the required behaviour?", vi: "Mô hình nào biểu đạt hành vi cần thiết rõ nhất?" }, topics: [["paradigms-and-procedural-design", "Recognise paradigm evidence", "Nhận diện bằng chứng của paradigm"], ["class-object-design-and-encapsulation", "Design protected object state", "Thiết kế state đối tượng được bảo vệ"], ["inheritance-polymorphism-and-aggregation", "Model is-a, has-a and dispatch", "Mô hình is-a, has-a và dispatch"], ["declarative-facts-rules-and-goals", "Prove a goal from facts and rules", "Chứng minh goal từ fact và rule"]] },
  { icon: Braces, title: { en: "Resolve and execute instructions", vi: "Resolve và thực thi lệnh" }, question: { en: "Where does the operand come from, and what state changes?", vi: "Operand đến từ đâu và state nào thay đổi?" }, topics: [["five-addressing-modes", "Resolve effective addresses", "Resolve effective address"], ["assembly-execution-and-construction", "Trace registers, memory and branches", "Trace register, memory và branch"]] },
  { icon: FileCog, title: { en: "Manage persistent data safely", vi: "Quản lý dữ liệu bền vững an toàn" }, question: { en: "How is a record located, changed and recovered when an operation fails?", vi: "Record được tìm, đổi và phục hồi khi thao tác lỗi như thế nào?" }, topics: [["serial-sequential-text-file-workflows", "Process records in sequence", "Xử lý record theo tuần tự"], ["random-file-record-operations", "Access a selected record directly", "Truy cập trực tiếp record đã chọn"], ["exceptions-and-controlled-recovery", "Route failure to recovery", "Chuyển lỗi sang nhánh phục hồi"]] },
] as const;

export function Chapter20Overview({ locale }: { readonly locale: Locale }) { const vi = locale === "vi"; return <section className={styles.overview} aria-labelledby="chapter20-overview-title"><div className={styles.heading}><div><span>{vi ? "LỘ TRÌNH ÔN THI" : "EXAM LEARNING ROUTE"}</span><h2 id="chapter20-overview-title">{vi ? "Chương trình tổ chức state, thực thi lệnh và phục hồi lỗi như thế nào?" : "How does a program organise state, execute instructions and recover from failure?"}</h2></div><p>{vi ? "Đừng bắt đầu bằng cú pháp. Hãy xác định model, state và operation trước; sau đó trace đúng convention của câu hỏi và kiểm tra điều kiện bảo vệ state." : "Do not begin with syntax. Identify the model, state and operation first; then trace the question's convention and check the condition that protects the state."}</p></div><div className={styles.branches} data-count={branches.length}>{branches.map((branch) => <article className={styles.branch} key={branch.title.en}><header><div><branch.icon size={22} aria-hidden="true" /><span>{vi ? "NHÁNH TƯ DUY" : "THINKING BRANCH"}</span></div><h3>{branch.title[locale]}</h3><p>{branch.question[locale]}</p></header><ol className={styles.route}>{branch.topics.map(([slug,en,viTitle], index) => <li key={slug}><Link href={paper3Href(`/paper-3/topics/${slug}`, locale)}><span className={styles.step}>{index + 1}</span><strong>{vi ? viTitle : en}</strong><ArrowUpRight size={16} aria-hidden="true" /></Link></li>)}</ol></article>)}</div><aside className={styles.prerequisite}><Layers3 size={22} aria-hidden="true" /><div><strong>{vi ? "Kiến thức cần gọi lại" : "Prerequisite checkpoint"}</strong><p>{vi ? "Ôn procedure/function, parameter, array/record, file mode và CPU register. Trong câu thi, tách blueprint khỏi object instance và tách logical record khỏi byte address." : "Recall procedures/functions, parameters, arrays/records, file modes and CPU registers. In exam answers, separate a blueprint from an object instance and a logical record from its byte address."}</p></div></aside></section>; }
